### ISSUE TITLE
Rewrite this in rust language?

### ISSUE THREAD

**Issue by jetbrains99** [OmkarPathak/pygorithm#12]
I think that this is an awesome way to learn things and am impressed a lot. So I want you to offer you a suggestion, rewrite this again in rust. If you don't know about rust, I would like to quote the famous rust lang book here -

> Rust is a programming language that’s focused on safety, speed, and concurrency. Its design lets you create programs that have the performance and control of a low-level language, but with the powerful abstractions of a high-level language. These properties make Rust suitable for programmers who have experience in languages like C and are looking for a safer alternative, as well as those from languages like Python who are looking for ways to write code that performs better without sacrificing expressiveness.

So I think this module will benefit a lot from a rewrite in rust lang and will improve its efficiency too while being completely safe of 99% of programming errors!

**Comment by OmkarPathak** [comment]
Well, Thank you for your kind words. I would definitely try the same thing in rust.
