### ISSUE TITLE
ModuleNotFoundError: No module named 'pygorithm.sorting'; 'pygorithm' is not a package

### ISSUE THREAD

**Issue by Jackson-Jack** [OmkarPathak/pygorithm#23]
After execute 'pip3 install pygorithm' successful, I use the first example code named 'To sort your list' ,but the run result is "ModuleNotFoundError: No module named 'pygorithm.sorting'; 'pygorithm' is not a package".  (ps: macOS Sierra, virtualenv,python3)

**Comment by AllstonMickey** [comment]
Try: export PYTHONPATH="$PYTHONPATH:/path/to/pygorithm"

**Comment by Jackson-Jack** [comment]
Thank you very much. I find it normal work without use virtualenv.
