### ISSUE TITLE
Suggestion: Alternative names

### ISSUE THREAD

**Issue by Skeen** [OmkarPathak/pygorithm#27]
Hi, 

I imagine a lot of algorithms have alternative names, which are also utilized frequently: say binsort vs bucketsort. Only having one name listed could be a source of confusion for students, who are only familiar with a synonymous term.

I therefore suggest adding a new method to the interface, aka: `alternative_names()`, which would return a (possibly empty) list of common synonyms.

**Comment by OmkarPathak** [comment]
@Skeen the idea is pretty good. But not many algorithms have alternate names or synonymous names. There are only a few. However, the idea is good hence we can add them to the documentation. Or if others vote on this positively, we can give a thought of adding `alternative_names()` in the interface.

**Comment by OmkarPathak** [comment]
Closing, because of no votes. If anybody thinks the same, he/she can reopen the issue.
