### ISSUE TITLE
bug in pygorithm.data_structures.tree.BSTNode.delete() ?

### ISSUE THREAD

**Issue by JeffyLu** [OmkarPathak/pygorithm#31]
https://github.com/OmkarPathak/pygorithm/blob/9e8434382688c1b41f88f907fef173bc6c37777d/pygorithm/data_structures/tree.py#L160
Is 'root' defined? 
someone tell me what's that mean, thanks!

**Comment by OmkarPathak** [comment]
Thanks for pointing it out. It was indeed a bug. Fixed!
