### ISSUE TITLE
Which Version of Python?

### ISSUE THREAD

**Issue by MrDupin** [OmkarPathak/pygorithm#36]
Hello!

A couple of years ago I wrote an implementation for [Tries](https://en.wikipedia.org/wiki/Trie). I am rewriting/updating it to post it here.

One question I have is whether I should make the code compatible with both Python 2 and 3. In the documentation you mention both, so I assume I need to make it backwards compatible?

**Comment by IanDoarn** [comment]
I'm not sure if its compatible with 2.7, I don't know if anyone has attempted to test in 2.7 either. I've been cleaning a lot of the code up and haven't noticed much backwards or forwards compatibility. Probably should aim for python 3 first then go back and make it compatible.

**Comment by OmkarPathak** [comment]
Searching, Sorting, math, string and fibonacci shouldn't have any problems with both versions of Python. However, some Data Structure parts would be incompatible
