### ISSUE TITLE
Error in pygorithm.geometry

### ISSUE THREAD

**Issue by OmkarPathak** [OmkarPathak/pygorithm#51]
`>>> from pygorithm.geometry import rect_broad_phase
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'pygorithm.geometry'`

This is the error that I am getting constantly. The code was merged from PR #50. Searching SO for error yielded that any circular dependency would cause such an error. But, there is no such dependency what so ever. @aesee can you see to it what's the problem?

**Comment by IanDoarn** [comment]
You're last commit broke how python reads packages, you need to revert the changes, __init__.py files are how python views imports. Please revert your latest changes!!

**Comment by OmkarPathak** [comment]
@IanDoarn other packages are working fine. The error I reported was caused as soon as I merged the PR

**Comment by IanDoarn** [comment]
@OmkarPathak still, they way you have the init.py's set up is entirely wrong and not at all PEP compliant

**Comment by OmkarPathak** [comment]
Okay. Reverting the changes
