### ISSUE TITLE
ImportError: cannot import name 'data_structures'

### ISSUE THREAD

**Issue by donatoaguirre24** [OmkarPathak/pygorithm#54]
I get that error for almost all modules less searching and sorting

'pip3 install pygorithm' successful
Windows 10 64 bits
Python 3.6.1 64 bits

**Comment by IanDoarn** [comment]
@donatoaguirre24 can you post the full traceback of your error?

**Comment by donatoaguirre24** [comment]
![issue](https://user-images.githubusercontent.com/20030075/29755486-3941129e-8b6f-11e7-9943-73f826073037.jpg)

**Comment by OmkarPathak** [comment]
@donatoaguirre24  somehow your Python path is not set correctly. Just check the path for your Python modules and try again.

**Comment by donatoaguirre24** [comment]
**Fixed**, uninstalled pygorithm and re-installed and everything started to work fine. The uninstalled package was 0.1.dev2 but when I reinstalled I got the 1.0.3 is strange but that explains why it did not work before. Thanks for the reply anyway.
