### ISSUE TITLE
Tests for different versions of Python

### ISSUE THREAD

**Issue by abramovd** [OmkarPathak/pygorithm#57]
How about using **tox** to run unittests for different versions of Python?

Besides, when I run `python3 -m unittest` (as suggested in README) all tests are passed, but there are some errors for `python2.7 -m unittest discover`. 

So, I'm not sure that Python 2.7 is fully supported, but it's stated in README that **"If you are using Python 2.7 use pip instead"**. 

So, I could try to add support for Python 2.x in PR and add a special note in README that only Python3.6 is supported for now.

**Comment by IanDoarn** [comment]
As I've been reformatting code I've been implementing some future imports but not many. Right now pygorithm is Python 3.x and not 2.7 compatible. Do we need to make it 2.7? Python 3 is the future of python so going backwards is probably not in the best interest of newer programmers to the language. Besides most major packages are migrating, or have migrated, to 3.x.

just my 2 cents but backporting seems a waste of time.

**Comment by OmkarPathak** [comment]
I agree with @IanDoarn Python3 is the future and many people are porting to Python3 (or rather are made to). So better that we keep Python3 as our preference for now.
