### ISSUE TITLE
Avoiding name conflicts in datastructures

### ISSUE THREAD

**Issue by Tjstretchalot** [OmkarPathak/pygorithm#59]
What are your thoughts on renaming all the Node classes to LinkedListNode, TreeNode, ect so it's less confusing if you're trying to test them out in idle?

**Comment by IanDoarn** [comment]
@Tjstretchalot How about a node class like nodes.py to import them from

Example:
```python
from pygorithm.data_structures.nodes import LinkedListNode, TreeNode
```
Or something like
```python
from pygorithm.data_structures.nodes import GenericNode
```

**Comment by Tjstretchalot** [comment]
Personally I prefer either one file per class or one file per algorithm. If you combined the nodes into one file that implies a stronger similarity between nodes of different structures than the similarity between the nodes and their containers, which would be a difficult argument to make

**Comment by IanDoarn** [comment]
@Tjstretchalot Then I feel we should go for one file __per algorithm__

**Comment by Tjstretchalot** [comment]
@IanDoarn and what about renaming them inside those files (the original question)?

**Comment by IanDoarn** [comment]
@Tjstretchalot  how do you mean?

**Comment by Tjstretchalot** [comment]
Right now we have the "Node" class in several locations (though implemented differently). I was wondering if anyone opposed renaming each respective one to something more specific. For example:

https://github.com/OmkarPathak/pygorithm/blob/master/pygorithm/data_structures/linked_list.py#L11

Change that line to def LinkedListNode (and update the other references)

**Comment by IanDoarn** [comment]
@Tjstretchalot I'm not opposed to it!

**Comment by OmkarPathak** [comment]
Yes I think Node class should be renamed.

**Comment by OmkarPathak** [comment]
I will rename the Node class with respected names in my next commit

**Comment by Tjstretchalot** [comment]
Perfect!
