### ISSUE TITLE
Branches, Deprication

### ISSUE THREAD

**Issue by IanDoarn** [OmkarPathak/pygorithm#60]
To everyone who has contributed.

We've been making quite a few changes recently and generally all the time now. Most of what I've been doing is fixing syntaxing to comply with PEP and in turn have been renaming quite a few things. I've noticed we've been renaming things or restructuring things. 

Here's my question(s) to you all:

**_Who all actively use this?_**

We change things a lot and this main repository does not have dev branches. Also, and I'm guilty of this, renaming things breaks code. Maybe we should have a dev branch now and also implement a way of warning the user of deprecation. In an old project of mine I implemented decorators for functions that where or were being deprecated.

Just my two cents!

**Comment by OmkarPathak** [comment]
I agree that we should have a development branch.

**Comment by IanDoarn** [comment]
@OmkarPathak would you be opposed to granting other people write permissions to this repo? Maybe the highest contributing people?

**Comment by OmkarPathak** [comment]
I would be happy to give write permissions. I am creating a dev branch and giving necessary permissions in sometime.

**Comment by IanDoarn** [comment]
@OmkarPathak :+1: Who will you be granting to? I think @Tjstretchalot is an excellent candidate

**Comment by Tjstretchalot** [comment]
I'm personally happy either way with committing to branches on the main repo and then pull requests into master or committing into my fork then pull requests into master. One advantage of on the main repo is we can see the live documentation without having separate links. One advantage to forks is you can rewrite history if you mess up and it won't be visible to anyone else (unless you have multiple people working on your fork of course)

**Comment by OmkarPathak** [comment]
I am giving write permissions to @Tjstretchalot as well as @IanDoarn :+1:

**Comment by OmkarPathak** [comment]
I have also created a dev branch. We three will be making changes on this branch and pushing the commits to the main branch whenever we feel right and all the codes runs without any errors.

**Comment by Tjstretchalot** [comment]
@OmkarPathak I pushed what I was about to push to my fork to dev to test. We should add a link to the documentation for the dev/ branch. This issue should help explain it: https://github.com/rtfd/readthedocs.org/issues/4

**Comment by OmkarPathak** [comment]
Just a little problem. I can't see dev branch in Readthedocs > Admin > Versions

**Comment by OmkarPathak** [comment]
Solved.
