### ISSUE TITLE
importing strings package

### ISSUE THREAD

**Issue by dutraneto** [OmkarPathak/pygorithm#65]
I tried import the package string like this:
**from pygorithm import strings** (like the documentation says).
But a only figured that when I typed:
**from pygorithm import string** (like the pypi repository)

**Comment by OmkarPathak** [comment]
Can you elaborate the problem with some of the error messages if possible

**Comment by IanDoarn** [comment]
@OmkarPathak when was the last time you updated to pypi repo using twine?

**Comment by IanDoarn** [comment]
@dutraneto For now download this repository and run ```python setup.py install``` I think the pypi repo is out of date and needs to be updated with our latest master branch

**Comment by OmkarPathak** [comment]
@IanDoarn I had updated the pypi repo about 2 weeks ago
