### ISSUE TITLE
Better way to do images?

### ISSUE THREAD

**Issue by Tjstretchalot** [OmkarPathak/pygorithm#69]
I am hoping for comment on my latest commit to the dev branch (https://github.com/OmkarPathak/pygorithm/commit/f044a65804362d2cd25f432b06a033e73d46c50a) specifically regarding this folder: https://github.com/OmkarPathak/pygorithm/tree/dev/imgs/test_geometry/test_extrapolated_intersection/out

It contains a lot of images that help me visualize what the tests are doing. They look like:

![ah04_test_line_line_intr_later](https://user-images.githubusercontent.com/931176/30081791-612d06d0-923d-11e7-8cbd-9e809dbd1f1a.png)

They are referenced as explained here: https://github.com/OmkarPathak/pygorithm/blob/dev/tests/test_geometry.py#L1455 
Do you think that it's fine that there are a *lot* of these files? I can't think of any good alternatives.

**Comment by OmkarPathak** [comment]
I think it's good. Let's go with this idea for now. :+1:

**Comment by IanDoarn** [comment]
How are you making them? It should be fine since they aren't packaged with the module, unless they are supposed to be

**Comment by Tjstretchalot** [comment]
I'm using [this](https://sourceforge.net/projects/graph/) program called "graph". It probably doesn't need to be packaged on pypy but I wonder if I should add a link to the github repo in the tests in case they come across the comments referencing it?

**Comment by IanDoarn** [comment]
@Tjstretchalot Maybe we could implement matplotlib?

**Comment by Tjstretchalot** [comment]
Ok so spent last couple hours working on what that would look like with matplotlib. The files generated would look something like:

![aa01_test_point_line_no_intr_2](https://user-images.githubusercontent.com/931176/30127024-a6ccb0d6-92f2-11e7-9264-f5c45d2b45e0.png)

as opposed to:

![aa01_test_point_line_no_intr](https://user-images.githubusercontent.com/931176/30127038-af28ee98-92f2-11e7-96c8-c540bfb6740f.png)

(after lots of configuration). No huge difference (though matplotlib has slightly better antialiasing).

Using that method I believe I could reduce the number of generating files by about a factor of 4 with the same number of images. That is to say, I could reduce it to one file per "type" of image. It wouldn't save any time, but is perhaps more portable?

Thoughts on that now that we can see them both? @OmkarPathak @IanDoarn

**Comment by Tjstretchalot** [comment]
I'm going to go with matplotlib from now on, I think with a larger initial investment it will make future ones easier
