### ISSUE TITLE
Syntax error in test.test_geometry

### ISSUE THREAD

**Issue by feynfan13** [OmkarPathak/pygorithm#72]
Hi, Omkar
Great work on the pygorithm project.
I am trying to run the unit test of the project and hit an syntax error in test.test_geometry.
It seems in line 1982, there is a missing left parentheses behind fn. Please check the code below

`# at03

intr, msg = fn((9.5, 8.5), (8.5, 7.5), (9.5, 5), (10.5, 7)), (0, 0), (-9, -9), ((2, 5), (-1, 5), (-2, 3), (2, 1), (3, 2)), reverse=True)

self.assertFalse(intr, msg=msg)`

Hope it helps. Thanks a lot.

**Comment by Tjstretchalot** [comment]
I think this is fixed in dev

**Comment by OmkarPathak** [comment]
Fixed in master as well! Thanks for reporting :+1:
