### ISSUE TITLE
BinaryTree class does not have adding-node functions

### ISSUE THREAD

**Issue by quocdat32461997** [OmkarPathak/pygorithm#81]
In tree.py, the BinaryTree class does not have functions which add nodes or delete nodes. There are only getting data functions only. 
If there is no special purposes for leaving the BinaryTree class without adding-node class, I will add adding-node functions the class.
![screenshot 66](https://user-images.githubusercontent.com/18373768/36760857-16434cfe-1be2-11e8-9278-797a3cbf23d6.png)

**Comment by OmkarPathak** [comment]
Yeah, that would be fine.. You can send PR for that! Thank You :smile:

**Comment by OmkarPathak** [comment]
I think we have addressed this issue. So I am closing this :smile:
