### ISSUE TITLE
Inclusion of International Competition Algorithms & Data Structures

### ISSUE THREAD

**Issue by ramlaxman** [OmkarPathak/pygorithm#83]
Adding algorithms from top International Competitions will help people to make this library useful for competitions. I believe we should focus on Syllabus of [International Olympiads of Informatics](http://ioi2017.org/files/ioi-syllabus-2017.pdf).

**Comment by OmkarPathak** [comment]
@ramlaxman sure. I am looking for some PRs from you. Happy contributing :+1: :smile:
